config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients, only:[:new, :create]
  resources :users, only:[:index, :show, :new]
  resources :recipes, only:[:index, :show, :new, :create]
  resources :ingredients, only:[:index, :show, :new]
end

app/models/allergen.rb
class Allergen < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
    has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
  end
end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
  def new
    @recipe_ingredient = RecipeIngredient.new
  end

  def create
    @recipe_ingredient = RecipeIngredient.create(ri_params)
    redirect_to recipe_path(@recipe_ingredient.recipe_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.create(recipe_params)
    
    params[:recipe][:ingredient_ids].each do |id|
      if id != nil
        RecipeIngredient.create(ingredient_id: id, recipe_id: @recipe.id)
      end
    end
    
    redirect_to @recipe
  end

  private

  def recipe_params
    params.require(:recipe).permit(:user_id, :name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<% @ingredients.each do |i| %>
    <h3><%= link_to i.name, ingredient_path(i) %></h3>
<% end %>

app/views/ingredients/new.html.erb
<h1>New Recipe Form</h1>

<%= form_with model: @recipe do |f| %>
    <label>Name: </label>
    <%= f.text_field :name %><br>
    <label>Ingredients: </label>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %><br>
    <label>User: </label>
    <%= f.collection_select :user_ids, User.all, :id, :name %><br>
    <%= f.submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>

<h3>Recipes that include <%= @ingredient.name %>:</h3>

<% @ingredient.recipes.each do |r| %>
    <p><%= link_to r.name, recipe_path(r) %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeAllergenApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipe_ingredients/new.html.erb
<h1>New RecipeIngredient Form</h1>

<%= form_with model: @recipe_ingredient do |f| %>
    <label>Name: </label>
    <%= f.text_field :name %><br>
    <label>User: </label>
    <%= f.collection_select :user_id, User.all, :id, :name %><br>
    <%= f.submit %>
<% end %>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<% @recipes.each do |r| %>
    <h3><%= link_to r.name, recipe_path(r) %></h3>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe Form</h1>

<%= form_with model: @recipe do |f| %>
    <label>Name: </label>
    <%= f.text_field :name %><br>
    <label>Ingredients: </label>
    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %><br>
    <label>User: </label>
    <%= f.collection_select :user_id, User.all, :id, :name %><br>
    <%= f.submit %>
<% end %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>

<h3>User: <%= @recipe.user.name %></h3>

<h3>Ingredients:</h3>
<% @recipe.ingredients.each do |i| %>
    <p><%= i.name %></p>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |u| %>
    <h3><%= link_to u.name, user_path(u) %></h3>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Recipes</h1>

<% @user.recipes.each do |r| %>
    <h3><%= r.name %></h3>
<% end %>